#!/bin/sh
# package versions

GDB_VER="16.3"

#NEWLIB_VER="4.5.0.20241231"
NEWLIB_VER="newlib%git@git://sourceware.org/git/newlib-cygwin.git@7d43942e7c3b56799e9e46c4701f86a8eb0ed579" #cygwin-3_6-branch 4.5.0+, cygwin-3.6.5+, 2025-12-04
NEWLIB_DNADR="${NEWLIB_VER}"

#OPENOCD_VER="0.12.0"
OPENOCD_VER="openocd%git@https://github.com/openocd-org/openocd.git@aa9ff8dc5ec60c46134f57a2f858149bb083036e" #main 0.12+, update on 2025-12-08
OPENOCD_DNADR="${OPENOCD_VER}"

# download addresses
GDB_DNADR="gdb%https://ftpmirror.gnu.org/gdb/gdb-${GDB_VER}.tar.xz"

NEWLIB_DNADR="${NEWLIB_DNADR:=newlib%ftp://sourceware.org/pub/newlib/newlib-${NEWLIB_VER}.tar.gz}"
OPENOCD_DNADR="${OPENOCD_DNADR:=openocd%http://sourceforge.net/projects/openocd/files/openocd/${OPENOCD_VER}/openocd-${OPENOCD_VER}.tar.bz2}"
