#!/bin/sh

#
# toolchain main component versions
# =================================
BINUTILS_VER="2.46.0"

#GCC_VER="15.2.0"
GCC_VER="gcc-15%git@https://github.com/gcc-mirror/gcc.git@cabffeef7f72114641e78a8e8ec6cb14526577f5" #releases/gcc-15 2026-04-01 15.2.x
GCC_DNADR="${GCC_VER}"

# toolchain package urls
BINUTILS_DNADR="${BINUTILS_DNADR:=binutils%https://ftpmirror.gnu.org/binutils/binutils-${BINUTILS_VER}.tar.xz}"
GCC_DNADR="${GCC_DNADR:=gcc%https://ftpmirror.gnu.org/gcc/gcc-${GCC_VER}/gcc-${GCC_VER}.tar.xz}"

#
# prerequisite versions
# =====================
ZLIB_NG_VER="2.3.3"
ZSTD_VER="1.5.7"
GMP_VER="6.3.0"
MPFR_VER="4.2.2"
MPC_VER="1.4.0"
ISL_VER="0.27"
EXPAT_VER="2.7.5"
ELFUTILS_VER="0.194"

# prerequisite package urls
ZLIB_NG_DNADR="zlib-ng%https://github.com/zlib-ng/zlib-ng/archive/refs/tags/${ZLIB_NG_VER}.tar.gz"
ZSTD_DNADR="zstd%https://github.com/facebook/zstd/releases/download/v${ZSTD_VER}/zstd-${ZSTD_VER}.tar.gz"
GMP_DNADR="gmp%https://gmplib.org/download/gmp/gmp-${GMP_VER}.tar.xz"
MPFR_DNADR="mpfr%https://www.mpfr.org/mpfr-current/mpfr-${MPFR_VER}.tar.xz"
MPC_DNADR="mpc%https://ftpmirror.gnu.org/mpc/mpc-${MPC_VER}.tar.xz"
ISL_DNADR="isl%https://libisl.sourceforge.io/isl-${ISL_VER}.tar.xz"
EXPAT_DNADR="expat%https://github.com/libexpat/libexpat/releases/download/R_${EXPAT_VER//./_}/expat-${EXPAT_VER}.tar.xz"
ELFUTILS_DNADR="elfutils%https://sourceware.org/elfutils/ftp/${ELFUTILS_VER}/elfutils-${ELFUTILS_VER}.tar.bz2"
