#!/bin/sh
# package versions

#LIBC_VER="2.2.1"
LIBC_VER="avr-libc%git@https://github.com/avrdudes/avr-libc.git@91f8b64207bc4bc9aeefd87f6844e27ef65a2b1d" #2.3.x-pre, 2025-11-24
LIBC_DNADR="${LIBC_VER}"

AVRDUDE_VER="8.1"

# download addresses
LIBC_DNADR="${LIBC_DNADR:=avr-libc%https://github.com/avrdudes/avr-libc/releases/download/avr-libc-${LIBC_VER//./_}-release/avr-libc-${LIBC_VER}.tar.bz2}"

AVRDUDE_DNADR="avrdude%https://github.com/avrdudes/avrdude/archive/refs/tags/v${AVRDUDE_VER}.tar.gz"
