#!/bin/sh
# package versions

#LIBC_VER="2.2.1"
LIBC_VER="avr-libc%git@https://github.com/avrdudes/avr-libc.git@8af880a773d7021b3533d0445e99a808ee682136" #main 2.3.1+, 2026-01-18
LIBC_DNADR="${LIBC_VER}"

AVRDUDE_VER="8.1"

# download addresses
LIBC_DNADR="${LIBC_DNADR:=avr-libc%https://github.com/avrdudes/avr-libc/releases/download/avr-libc-${LIBC_VER//./_}-release/avr-libc-${LIBC_VER}.tar.bz2}"

AVRDUDE_DNADR="avrdude%https://github.com/avrdudes/avrdude/archive/refs/tags/v${AVRDUDE_VER}.tar.gz"
